# Generated by Django 5.0 on 2026-01-26 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_alter_storymodel_options_storymodel_author_name_and_more'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_stories', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.storymodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'story')},
            },
        ),
        migrations.CreateModel(
            name='StudentSavedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definition', models.TextField(blank=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'word')},
            },
        ),
    ]
