# Generated by Django 5.0 on 2026-01-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storymodel',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Stories'},
        ),
        migrations.AddField(
            model_name='storymodel',
            name='author_name',
            field=models.CharField(blank=True, default='Admin', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storymodel',
            name='grade',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='storymodel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='storymodel',
            name='total_pages',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
